spring.application.name=rate-limiting
#spring.profiles.active=${SPRING_PROFILE:docker}

feature.default.rate-limiting.enabled=${USE_DEFAULT_RATE_LIMITING:false}

settings.use.sliding.window.rate.limiting=${USE_SLIDING_WINDOW:true}
settings.rate.limit=${RATE_LIMIT:100}
settings.rate.limit.window.seconds=${RATE_LIMIT_WINDOW_SECONDS:15}

#redis
spring.data.redis.host=${REDIS_HOST:host.docker.internal}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=${CACHE_TYPE:redis}