spring.application.name=rate-limiting
server.port=8080

feature.rate.limiting.filter=bucket4j

settings.use.sliding.window.rate.limiting=true
settings.rate.limit=100
settings.burst.rate.limit=20
settings.rate.limit.window.seconds=15
settings.use.scheduled.refiller=false
settings.token.refill.per.second=2

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis