spring.application.name=rate-limiting
server.port=8080

feature.default.rate-limiting.enabled=false

settings.use.sliding.window.rate.limiting=true
settings.rate.limit=100
settings.rate.limit.window.seconds=15

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis