spring.application.name=rate-limiting

settings.use.sliding.window.rate.limiting=${USE_SLIDING_WINDOW}
settings.rate.limit=${RATE_LIMIT}
settings.rate.limit.window.seconds=${RATE_LIMIT_WINDOW_SECONDS}