spring.application.name=rate-limiting
#spring.profiles.active=${SPRING_PROFILE:docker}

feature.rate.limiting.filter=${FEATURE_RATE_LIMITING_FILTER:token-bucket}

settings.use.sliding.window.rate.limiting=${USE_SLIDING_WINDOW:true}
settings.rate.limit=${RATE_LIMIT:100}
settings.burst.rate.limit=${BURST_RATE_LIMIT:20}
settings.rate.limit.window.seconds=${RATE_LIMIT_WINDOW_SECONDS:15}
settings.use.scheduled.refiller=${USE_SCHEDULED_REFILLER:false}
settings.token.refill.per.second=${TOKEN_REFILL_PER_SECOND:2}

#redis
spring.data.redis.host=${REDIS_HOST:host.docker.internal}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=${CACHE_TYPE:redis}